sudo: required
services:
  - docker

before_install:
  - docker build -t a1r93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true a1r93/react-test npm run test

after_success:
  - docker build -t a1r93/multi-client ./client
  - docker build -t a1r93/multi-nginx ./nginx
  - docker build -t a1r93/multi-server ./server
  - docker build -t a1r93/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then to docker hub
  - docker push a1r93/multi-client
  - docker push a1r93/multi-nginx
  - docker push a1r93/multi-server
  - docker push a1r93/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-145115518065
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
